# Use root/example as user/password credentials
version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_DB=project2-database2
      - MYSQL_USER=missy
      - MYSQL_PASSWORD=missy
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=project2-database2
      - MYSQL_USER=missy
      - MYSQL_PASSWORD=missy
      